version: '3.8'

services:
  auth_db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: auth_db
    networks:
      - backend

  notif_db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: notif_db
    volumes:
      - notif_db_data:/var/lib/postgresql/data
    networks:
      - backend

  vehicle_db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: vehicle_db
    networks:
      - backend

  traffic_db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: traffic_db
    networks:
      - backend

  incident_db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: incident_db
    networks:
      - backend

  auth-service:
    build: ./auth-service
    environment:
      DB_HOST: auth_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: auth_db
      JWT_SECRET: supersecretkey123
      PORT: 3001
    depends_on:
      - auth_db
    networks:
      - backend

  notif-service:
    ports: 
      - "3002:3002"
    build: ./notif-service
    environment:
      DB_HOST: notif_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: notif_db
      PORT: 3002
      AUTH_SERVICE: http://auth-service:3001
    depends_on:
      - notif_db
    networks:
      - backend

  vehicle-service:
    build: ./vehicle-service
    environment:
      DB_HOST: vehicle_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: vehicle_db
      PORT: 3003
      NOTIF_SERVICE: http://notif-service:3002
    depends_on:
      - vehicle_db
    networks:
      - backend

  traffic-service:
    build: ./traffic-service
    environment:
      DB_HOST: traffic_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: traffic_db
      PORT: 3004
      NOTIF_SERVICE: http://notif-service:3002
    depends_on:
      - traffic_db
    networks:
      - backend

  incident-service:
    build: ./incident-service
    environment:
      DB_HOST: incident_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: incident_db
      NOTIF_SERVICE: http://notif-service:3002
      PORT: 3005
    depends_on:
      - incident_db
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      JWT_SECRET: supersecretkey123
      AUTH_SERVICE: http://auth-service:3001
      NOTIF_SERVICE: http://notif-service:3002
      VEHICLE_SERVICE: http://vehicle-service:3003
      TRAFFIC_SERVICE: http://traffic-service:3004
      INCIDENT_SERVICE: http://incident-service:3005
    depends_on:
      - auth-service
      - notif-service
      - vehicle-service
      - traffic-service
      - incident-service
    networks:
      - backend
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/api/v1
    depends_on:
      - api-gateway
    networks:
      - frontend

volumes:
  notif_db_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge